// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARMnQ27aRdJ-PO1NTfcosuZ2Umm3M4Xzo',
    appId: '1:521686955983:web:652ae38a7688bd080244ba',
    messagingSenderId: '521686955983',
    projectId: 'fishtrace-1edac',
    authDomain: 'fishtrace-1edac.firebaseapp.com',
    databaseURL: 'https://fishtrace-1edac-default-rtdb.firebaseio.com',
    storageBucket: 'fishtrace-1edac.firebasestorage.app',
    measurementId: 'G-K87RGZHCH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMrz3HnR08UBa0XcoAGbGzx_MnqG88LwQ',
    appId: '1:521686955983:android:515a1e382354b8a60244ba',
    messagingSenderId: '521686955983',
    projectId: 'fishtrace-1edac',
    databaseURL: 'https://fishtrace-1edac-default-rtdb.firebaseio.com',
    storageBucket: 'fishtrace-1edac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoGyBFDVwmatgL8y1JPII-ycmyvP6S9-w',
    appId: '1:521686955983:ios:36b224eb86cdf86b0244ba',
    messagingSenderId: '521686955983',
    projectId: 'fishtrace-1edac',
    databaseURL: 'https://fishtrace-1edac-default-rtdb.firebaseio.com',
    storageBucket: 'fishtrace-1edac.firebasestorage.app',
    iosBundleId: 'com.example.fishtrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoGyBFDVwmatgL8y1JPII-ycmyvP6S9-w',
    appId: '1:521686955983:ios:36b224eb86cdf86b0244ba',
    messagingSenderId: '521686955983',
    projectId: 'fishtrace-1edac',
    databaseURL: 'https://fishtrace-1edac-default-rtdb.firebaseio.com',
    storageBucket: 'fishtrace-1edac.firebasestorage.app',
    iosBundleId: 'com.example.fishtrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARMnQ27aRdJ-PO1NTfcosuZ2Umm3M4Xzo',
    appId: '1:521686955983:web:34612e4462128dc80244ba',
    messagingSenderId: '521686955983',
    projectId: 'fishtrace-1edac',
    authDomain: 'fishtrace-1edac.firebaseapp.com',
    databaseURL: 'https://fishtrace-1edac-default-rtdb.firebaseio.com',
    storageBucket: 'fishtrace-1edac.firebasestorage.app',
    measurementId: 'G-TBC9GG66CJ',
  );
}
